### ISSUE TITLE
uninitialized constant Spree::Admin::ProductsController

### ISSUE THREAD

**Issue by matiasmansilla1989** [spree-contrib/spree-multi-domain#122]
Hello, I created a rails 4.1.6 project and then I added to my gemfile 
gem 'spree_multi_domain', git: 'git://github.com/spree/spree-multi-domain.git'

Then when I run: 
bundle exec rails g spree_multi_domain:install 

I get the next error: 
uninitialized constant Spree::Admin::ProductsController (NameError)

/Users/toptierlabs/.rvm/gems/ruby-2.1.1/bundler/gems/spree-multi-domain-c8782907a414/app/controllers/spree/admin/products_controller_decorator.rb:1:in `<top (required)>': uninitialized constant Spree::Admin::ProductsController (NameError)
	from /Users/toptierlabs/.rvm/gems/ruby-2.1.1/bundler/gems/spree-multi-domain-c8782907a414/lib/spree_multi_domain/engine.rb:10:in `block (2 levels) in activate'
	from /Users/toptierlabs/.rvm/gems/ruby-2.1.1/bundler/gems/spree-multi-domain-c8782907a414/lib/spree_multi_domain/engine.rb:9:in `glob'
	from /Users/toptierlabs/.rvm/gems/ruby-2.1.1/bundler/gems/spree-multi-domain-c8782907a414/lib/spree_multi_domain/engine.rb:9:in `block in activate'
	from /Users/toptierlabs/.rvm/gems/ruby-2.1.1/bundler/gems/spree-multi-domain-c8782907a414/lib/spree_multi_domain/engine.rb:8:in `each'
	from /Users/toptierlabs/.rvm/gems/ruby-2.1.1/bundler/gems/spree-multi-domain-c8782907a414/lib/spree_multi_domain/engine.rb:8:in `activate'
.....

I was looking into the repo but I don't have idea what happen.

Thanks, Matias

**Comment by krtschmr** [comment]
Matias;

You need to install `spree` first. spree_multi_domain is just an extension *on-top* of spree.
