### ISSUE TITLE
Tests dont run

### ISSUE THREAD

**Issue by schmijos** [spree-contrib/spree-multi-domain#126]
When running `bundle exec rake test_app` on the branch *2-4-stable* the following error is shown:

```bash
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `logo_file_name' for #<Spree::Store:0x007fc95ec13228>/Users/josua/projects/spree-multi-domain/spec/dummy/db/migrate/20150428123338_create_store_from_preferences.spree.rb:35:in `change'
NoMethodError: undefined method `logo_file_name' for #<Spree::Store:0x007fc95ec13228>
/Users/josua/projects/spree-multi-domain/spec/dummy/db/migrate/20150428123338_create_store_from_preferences.spree.rb:35:in `change'
```

The problem seems to be the *paperclip* validation in `store_decorator.rb`. If you comment that out, it's possible to create the *test_app*. But even then the tests don't run.

**Comment by timberkeley** [comment]
I got the tests to run in 2-4-stable by changing the following:

app/models/spree/store_decorator.rb

```
-    validates_attachment_file_name :logo, :matches => [/png\Z/i, /jpe?g\Z/i]
+    if respond_to? :logo_file_name 
+      validates_attachment_file_name :logo, :matches => [/png\Z/i, /jpe?g\Z/i]
+    end
```

lib/generators/spree_multi_domain/install/install_generator.rb

```
       def add_migrations
-        run 'rake railties:install:migrations FROM=spree_multi_domain'
+        run 'bundle exec rake railties:install:migrations FROM=spree_multi_domain'
       end
```

spree_multi_domain.gemspec

```
   s.add_development_dependency 'coffee-rails'
-  s.add_development_dependency 'factory_girl', '~> 4.3.0'
+  s.add_development_dependency 'factory_girl', '~> 4.5.0'
   s.add_development_dependency 'ffaker'
```

then 

bundle exec rake test_app
bundle exec rspec spec

Now I can't access the admin section if I run the dummy app with

```
cd spec/dummy
bundle exec rails s -e test
```

It just redirects back to the store home page.
