### ISSUE TITLE
loading Taxons fails on spree 3.2.1

### ISSUE THREAD

**Issue by ignaciosm** [spree-contrib/spree-multi-domain#167]
Hi,
I just installed a clean version of spree 3.2.1 and when adding the multi-domain extension Taxons don't load...I get an error "Loading failed" in both the taxons section of the admin and inside the product section of the admin.

Any ideas as to how to fix this?
Thanks!

**Comment by raulpopadineti** [comment]
same issue here as @ignaciosm

**Comment by raulpopadineti** [comment]
To give you more insight, this is the error I'm getting:

```
NoMethodError (Could not render layout: undefined method `compact' for nil:NilClass):
  
actionview (5.0.3) lib/action_view/layouts.rb:412:in `rescue in _default_layout'
actionview (5.0.3) lib/action_view/layouts.rb:409:in `_default_layout'
actionview (5.0.3) lib/action_view/layouts.rb:386:in `block in _layout_for_option'
/Users/ma3x/Work/vld/spree-multi-domain/lib/spree_multi_domain/engine.rb:30:in `find_layout_with_multi_store'
actionview (5.0.3) lib/action_view/renderer/template_renderer.rb:60:in `render_with_layout'
actionview (5.0.3) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
actionview (5.0.3) lib/action_view/renderer/template_renderer.rb:14:in `render'
actionview (5.0.3) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionview (5.0.3) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (5.0.3) lib/action_view/rendering.rb:104:in `_render_template'
actionpack (5.0.3) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (5.0.3) lib/action_view/rendering.rb:83:in `render_to_body'
actionpack (5.0.3) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (5.0.3) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
actionpack (5.0.3) lib/abstract_controller/rendering.rb:26:in `render'
actionpack (5.0.3) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (5.0.3) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (5.0.3) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/Users/ma3x/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
```

I'm using POW for my local environment and this is my store:

```
<Spree::Store id: 1, url: "pasio.dev", mail_from_address: "office@pasio.dev", default_currency: "USD", code: "spree", default: true, created_at: "2017-05-29 08:38:08", updated_at: "2017-06-25 21:20:41", logo_file_name: "logo.png", logo_content_type: "image/png">
```

I did not add any layouts in my `app/views/spree/layouts` as I think it should pick up the default spree layout, right?

**Comment by bartlomiejmatlega** [comment]
Same problem as @ignaciosm and @raulpopadineti :( Have you found a fix ?
